project:
  type: website
  # execute-dir: project
  preview:
    port: 4200
title-block-banner: true
execute: 
  echo: false
pdf-engine: latexmk
format:
  html:
    embed-resources: true
    smooth-scroll: true
    code-fold: false
    toc: true
    toc-location: left
    fig-width: 8
    fig-height: 7
    theme:
      # light: flatly
      light: lumen
      dark: darkly
    css: style.css
    page-layout: full
  docx:
    page-width: 7.5