name: Render and deploy quarto files
on:
  push:
    branches: main
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Update apt-get
      run: sudo apt-get update
        
    # - name: Set up R (needed for Rmd)
    #   uses: r-lib/actions/setup-r@v2
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        # To install LaTeX to build PDF book 
        tinytex: true 
        # uncomment below and fill to pin a version
        # version: 0.9.600
        version: v2025.04

    - name: Render and Publish to GitHub Pages
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
